# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-11 17:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ubicacion', '0001_initial'),
        ('actividades', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='ubicacion.DepartamentoInstancia'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='facultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='ubicacion.FacultadInstancia'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_actividades.actividad_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='ubicacion.Sede'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='titulo',
            name='centro_estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.CentroEstudio'),
        ),
        migrations.AddField(
            model_name='titulo',
            name='info_titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.InfoTitulo'),
        ),
        migrations.AlterUniqueTogether(
            name='libro',
            unique_together=set([('isbn',)]),
        ),
        migrations.AlterUniqueTogether(
            name='investigacion',
            unique_together=set([('codigo',)]),
        ),
        migrations.AlterUniqueTogether(
            name='actividad',
            unique_together=set([('usuario', 'nombre_actividad')]),
        ),
    ]
