# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-11 17:28
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('h', 'Hombre'), ('m', 'Mujer')], max_length=1, null=True)),
                ('provincia', models.CharField(blank=True, choices=[('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09')], max_length=5, null=True)),
                ('clase', models.CharField(blank=True, choices=[('00', '00'), ('N', 'N'), ('E', 'E'), ('EC', 'EC'), ('PE', 'PE'), ('AV', 'AV'), ('PI', 'PI')], max_length=5, null=True)),
                ('tomo', models.CharField(blank=True, max_length=5, null=True)),
                ('folio', models.CharField(blank=True, max_length=5, null=True)),
                ('imagen', models.ImageField(blank=True, upload_to='perfil/')),
                ('categoria', models.CharField(blank=True, choices=[('1', 'Tiempo Completo'), ('2', 'Tiempo Parcial')], max_length=1, null=True)),
                ('pais', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('cod_profesor', models.CharField(blank=True, max_length=120, null=True)),
                ('cod_sede', models.CharField(blank=True, default='XX', max_length=2, null=True)),
                ('cod_facultad', models.CharField(blank=True, default='XX', max_length=2, null=True)),
                ('cod_escuela', models.CharField(blank=True, default='XX', max_length=2, null=True)),
                ('cod_departamento', models.CharField(blank=True, default='XX', max_length=2, null=True)),
            ],
            options={
                'verbose_name_plural': 'Perfiles',
                'permissions': (('ver_perfil', 'Ver Perfil'),),
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=120)),
                ('texto', models.CharField(max_length=120)),
                ('url', models.URLField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
