# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-17 23:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_facultad', models.CharField(max_length=2)),
                ('cod_escuela', models.CharField(max_length=2)),
                ('cod_carrera', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('R', 'Regular'), ('P', 'Postgrado'), ('M', 'Maestria'), ('D', 'Doctorado'), ('C', 'Curso / Diplomado')], default='R', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='CarreraInstancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_sede', models.CharField(max_length=2)),
                ('cod_facultad', models.CharField(max_length=2)),
                ('cod_escuela', models.CharField(max_length=2)),
                ('cod_carrera', models.CharField(max_length=2)),
                ('activo', models.BooleanField(default=True)),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='ubicacion.Carrera')),
            ],
            options={
                'verbose_name_plural': 'Instancias Carreras',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_facultad', models.CharField(max_length=2)),
                ('cod_departamento', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=120)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='DepartamentoInstancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_sede', models.CharField(max_length=2)),
                ('cod_facultad', models.CharField(max_length=2)),
                ('cod_departamento', models.CharField(max_length=2)),
                ('activo', models.BooleanField(default=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubicacion.Departamento')),
            ],
            options={
                'verbose_name_plural': 'Instancias Departamento',
            },
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_facultad', models.CharField(max_length=2)),
                ('cod_escuela', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('ES', 'Escuela'), ('DE', 'Departamento'), ('CO', 'Comision'), ('DC', 'Decanato')], default='ES', max_length=2)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Escuelas y Departamentos',
            },
        ),
        migrations.CreateModel(
            name='EscuelaInstancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_sede', models.CharField(max_length=2)),
                ('cod_facultad', models.CharField(max_length=2)),
                ('cod_escuela', models.CharField(max_length=2)),
                ('activo', models.BooleanField(default=True)),
                ('escuela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escuelas', to='ubicacion.Escuela')),
            ],
            options={
                'verbose_name_plural': 'Instancias Secciones',
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_facultad', models.CharField(max_length=2, unique=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('tipo', models.CharField(choices=[('FA', 'Facultad'), ('VI', 'Vicerrectoria')], default='FA', max_length=2)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Facultades',
            },
        ),
        migrations.CreateModel(
            name='FacultadInstancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('cod_sede', models.CharField(max_length=2)),
                ('cod_facultad', models.CharField(max_length=2)),
                ('decano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('facultad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instancias', to='ubicacion.Facultad')),
            ],
            options={
                'verbose_name_plural': 'Instancias Facultades',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_sede', models.CharField(max_length=2, unique=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('tipo', models.CharField(choices=[('CU', 'Campus'), ('CR', 'Centro Regional'), ('EX', 'Extension'), ('PA', 'Proyecto Anexo')], default='PA', max_length=2)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Sedes',
            },
        ),
        migrations.AddField(
            model_name='facultadinstancia',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facultades', to='ubicacion.Sede'),
        ),
        migrations.AddField(
            model_name='escuelainstancia',
            name='facultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escuelas', to='ubicacion.Facultad'),
        ),
        migrations.AddField(
            model_name='escuelainstancia',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escuelas', to='ubicacion.Sede'),
        ),
        migrations.AddField(
            model_name='escuelainstancia',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escuelas', to='ubicacion.FacultadInstancia'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='facultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ubicacion.Facultad'),
        ),
        migrations.AddField(
            model_name='departamentoinstancia',
            name='facultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubicacion.Facultad'),
        ),
        migrations.AddField(
            model_name='departamentoinstancia',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='ubicacion.Sede'),
        ),
        migrations.AddField(
            model_name='departamentoinstancia',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='ubicacion.FacultadInstancia'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='facultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ubicacion.Facultad'),
        ),
        migrations.AddField(
            model_name='carrerainstancia',
            name='escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='ubicacion.Escuela'),
        ),
        migrations.AddField(
            model_name='carrerainstancia',
            name='facultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='ubicacion.Facultad'),
        ),
        migrations.AddField(
            model_name='carrerainstancia',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='ubicacion.Sede'),
        ),
        migrations.AddField(
            model_name='carrerainstancia',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='ubicacion.EscuelaInstancia'),
        ),
        migrations.AddField(
            model_name='carrerainstancia',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='ubicacion.FacultadInstancia'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='facultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubicacion.Facultad'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubicacion.Escuela'),
        ),
        migrations.AlterUniqueTogether(
            name='facultadinstancia',
            unique_together=set([('cod_sede', 'cod_facultad')]),
        ),
        migrations.AlterUniqueTogether(
            name='escuelainstancia',
            unique_together=set([('cod_sede', 'cod_facultad', 'cod_escuela')]),
        ),
        migrations.AlterUniqueTogether(
            name='escuela',
            unique_together=set([('cod_escuela', 'cod_facultad')]),
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together=set([('cod_facultad', 'cod_departamento')]),
        ),
        migrations.AlterUniqueTogether(
            name='carrerainstancia',
            unique_together=set([('cod_sede', 'cod_facultad', 'cod_escuela', 'cod_carrera')]),
        ),
        migrations.AlterUniqueTogether(
            name='carrera',
            unique_together=set([('cod_facultad', 'cod_escuela', 'cod_carrera')]),
        ),
    ]
