# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-17 23:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(blank=True, max_length=120)),
                ('segundo_nombre', models.CharField(blank=True, max_length=120)),
                ('primer_apellido', models.CharField(blank=True, max_length=120)),
                ('segundo_apellido', models.CharField(blank=True, max_length=120)),
                ('nombre_completo', models.CharField(blank=True, max_length=480)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('h', 'Hombre'), ('m', 'Mujer')], max_length=1, null=True)),
                ('provincia', models.CharField(blank=True, choices=[('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09')], default='00', max_length=5, null=True)),
                ('clase', models.CharField(blank=True, choices=[('00', '00'), ('N', 'N'), ('E', 'E'), ('EC', 'EC'), ('PE', 'PE'), ('AV', 'AV'), ('PI', 'PI')], default='00', max_length=5, null=True)),
                ('tomo', models.CharField(blank=True, default='000', max_length=5, null=True)),
                ('folio', models.CharField(blank=True, default='0000', max_length=5, null=True)),
                ('imagen', models.ImageField(blank=True, upload_to='perfil/')),
                ('categoria', models.CharField(blank=True, choices=[('1', 'Tiempo Completo'), ('2', 'Tiempo Parcial')], max_length=1, null=True)),
                ('pais', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('cod_profesor', models.CharField(blank=True, max_length=120, null=True)),
                ('cod_sede', models.CharField(blank=True, default='XX', max_length=2, null=True)),
                ('cod_facultad', models.CharField(blank=True, default='XX', max_length=2, null=True)),
                ('cod_escuela', models.CharField(blank=True, default='XX', max_length=2, null=True)),
                ('cod_departamento', models.CharField(blank=True, default='XX', max_length=2, null=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='ubicacion.DepartamentoInstancia')),
                ('escuela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrativos', to='ubicacion.EscuelaInstancia')),
                ('facultad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal', to='ubicacion.FacultadInstancia')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal', to='ubicacion.Sede')),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Perfiles',
            },
        ),
    ]
