# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-11 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_auto_20180405_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'permissions': (('ver_perfil', 'Ver Perfil'),), 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterField(
            model_name='perfil',
            name='clase',
            field=models.CharField(blank=True, choices=[('00', '00'), ('N', 'N'), ('E', 'E'), ('EC', 'EC'), ('PE', 'PE'), ('AV', 'AV'), ('PI', 'PI')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='folio',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='provincia',
            field=models.CharField(blank=True, choices=[('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tomo',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='perfil',
            unique_together=set([('provincia', 'clase', 'tomo', 'folio')]),
        ),
    ]
