# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-03 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='anteproyecto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiantes.Anteproyecto'),
        ),
    ]
