# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-04 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_auto_20180403_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anteproyecto',
            name='archivo',
            field=models.FileField(blank=True, upload_to='anteproyectos'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='archivo',
            field=models.FileField(blank=True, upload_to='proyectos'),
        ),
    ]
