# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-11 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0004_auto_20180404_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={},
        ),
    ]
