# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-11 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0005_auto_20180411_1142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyecto',
            new_name='TrabajoGraduacion',
        ),
    ]
