# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-12 02:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.uploads
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ubicacion', '0002_auto_20180411_1142'),
        ('estudiantes', '0006_auto_20180411_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anteproyecto',
            name='asesor',
        ),
        migrations.RemoveField(
            model_name='anteproyecto',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='anteproyecto',
            name='escuela',
        ),
        migrations.RemoveField(
            model_name='anteproyecto',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='anteproyecto',
            name='facultad',
        ),
        migrations.RemoveField(
            model_name='anteproyecto',
            name='registrado_por',
        ),
        migrations.RemoveField(
            model_name='anteproyecto',
            name='sede',
        ),
        migrations.AlterModelOptions(
            name='trabajograduacion',
            options={'permissions': (('aprobar_trabajo', 'Aprobar Trabajo'),)},
        ),
        migrations.RemoveField(
            model_name='trabajograduacion',
            name='anteproyecto',
        ),
        migrations.RemoveField(
            model_name='trabajograduacion',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='trabajograduacion',
            name='detalle',
        ),
        migrations.AddField(
            model_name='trabajograduacion',
            name='archivo_anteproyecto',
            field=models.FileField(blank=True, upload_to=utils.uploads.anteproyecto_upload_rename, validators=[utils.validators.validate_file_type]),
        ),
        migrations.AddField(
            model_name='trabajograduacion',
            name='archivo_trabajo',
            field=models.FileField(blank=True, upload_to=utils.uploads.anteproyecto_upload_rename, validators=[utils.validators.validate_file_type]),
        ),
        migrations.AddField(
            model_name='trabajograduacion',
            name='asesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asesorias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trabajograduacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('rechazado', 'Rechazado'), ('aprobado', 'Aprobado')], default='pendiente', max_length=15),
        ),
        migrations.AddField(
            model_name='trabajograduacion',
            name='nombre_proyecto',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='trabajograduacion',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trabajograduacion',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_graduacion', to='ubicacion.Sede'),
        ),
        migrations.AlterField(
            model_name='trabajograduacion',
            name='carrera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_graduacion', to='ubicacion.CarreraInstancia'),
        ),
        migrations.AlterField(
            model_name='trabajograduacion',
            name='escuela',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_graduacion', to='ubicacion.EscuelaInstancia'),
        ),
        migrations.AlterField(
            model_name='trabajograduacion',
            name='facultad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_graduacion', to='ubicacion.FacultadInstancia'),
        ),
        migrations.DeleteModel(
            name='Anteproyecto',
        ),
    ]
