# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-12 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0007_auto_20180411_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajograduacion',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_graduacion', to='ubicacion.CarreraInstancia'),
        ),
        migrations.AlterField(
            model_name='trabajograduacion',
            name='escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_graduacion', to='ubicacion.EscuelaInstancia'),
        ),
        migrations.AlterField(
            model_name='trabajograduacion',
            name='facultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_graduacion', to='ubicacion.FacultadInstancia'),
        ),
    ]
