# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-12 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0008_auto_20180411_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajograduacion',
            old_name='estudiante',
            new_name='estudiantes',
        ),
    ]
