# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-12 20:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0009_auto_20180412_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajograduacion',
            name='jurados',
            field=models.ManyToManyField(blank=True, null=True, related_name='jurado', to=settings.AUTH_USER_MODEL),
        ),
    ]
