# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-17 21:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0012_auto_20180412_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajograduacion',
            name='asesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asesorias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trabajograduacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('rechazado', 'Rechazado'), ('aprobado', 'Aprobado'), ('sustentado', 'Sustentado')], default='pendiente', max_length=15),
        ),
    ]
