# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-26 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0014_auto_20180423_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajograduacion',
            name='fecha_actualizacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trabajograduacion',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
