# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-26 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0015_auto_20180425_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajograduacion',
            old_name='fecha_registro',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fecha_actualizacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
